/*
 * TTI-O Java Implementation
 * Copyright (C) 2026 DTW-Thalion
 * SPDX-License-Identifier: LGPL-3.0-or-later
 */
package com.dtwthalion.ttio.importers;

import com.dtwthalion.ttio.Feature;
import com.dtwthalion.ttio.Identification;
import com.dtwthalion.ttio.importers.MzTabReader.MzTabImport;

import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * M78 cross-language conformance gate — Java side. Reads the shared
 * fixtures at {@code conformance/mztab_features/} generated by the
 * Python reference implementation and asserts that the Java mzTab
 * importer extracts the same Feature content.
 *
 * <p>Parity target: {@code python/tests/test_m78_mztab_conformance.py}.</p>
 */
class MzTabReaderM78ConformanceTest {

    private static Path findConformanceDir() {
        Path here = Paths.get("").toAbsolutePath();
        for (int up = 0; up < 6; up++) {
            Path probe = here.resolve("conformance").resolve("mztab_features");
            if (Files.isDirectory(probe)) return probe;
            if (here.getParent() == null) break;
            here = here.getParent();
        }
        return null;
    }

    @Test
    void proteomicsFixtureHasTwoPeptideFeatures() throws IOException {
        Path conf = findConformanceDir();
        Assumptions.assumeTrue(conf != null,
            "conformance/mztab_features not reachable from CWD");
        Path fixture = conf.resolve("proteomics.mztab");
        Assumptions.assumeTrue(Files.isRegularFile(fixture),
            "fixture not present: " + fixture);

        MzTabImport parsed = MzTabReader.read(fixture);
        assertEquals("1.0", parsed.version());
        assertEquals(2, parsed.features().size());

        Map<String, Feature> bySeq = new HashMap<>();
        for (Feature f : parsed.features()) bySeq.put(f.chemicalEntity(), f);
        assertTrue(bySeq.containsKey("AAAAPEPTIDER"),
            "AAAAPEPTIDER feature present");
        assertTrue(bySeq.containsKey("QWERTYK"),
            "QWERTYK feature present");
        assertEquals(2, bySeq.get("AAAAPEPTIDER").charge());
        assertEquals(615.329, bySeq.get("AAAAPEPTIDER").expMassToCharge(), 1e-2);
        assertEquals(1, bySeq.get("QWERTYK").charge());
    }

    @Test
    void metabolomicsFixtureHasTwoSmallMoleculeFeatures() throws IOException {
        Path conf = findConformanceDir();
        Assumptions.assumeTrue(conf != null,
            "conformance/mztab_features not reachable from CWD");
        Path fixture = conf.resolve("metabolomics.mztab");
        Assumptions.assumeTrue(Files.isRegularFile(fixture),
            "fixture not present: " + fixture);

        MzTabImport parsed = MzTabReader.read(fixture);
        assertEquals("2.0.0-M", parsed.version());
        assertEquals(2, parsed.features().size());

        Map<String, Feature> byAdduct = new HashMap<>();
        for (Feature f : parsed.features()) byAdduct.put(f.adductIon(), f);
        assertTrue(byAdduct.containsKey("[M+H]1+"));
        assertTrue(byAdduct.containsKey("[M+Na]1+"));
        // After SME back-fill, chemical_entity resolves to database_identifier.
        assertEquals("CHEBI:15377", byAdduct.get("[M+H]1+").chemicalEntity());
        assertEquals("CHEBI:16865", byAdduct.get("[M+Na]1+").chemicalEntity());
    }

    @Test
    void metabolomicsFixtureSmeRowsPreserveConfidence() throws IOException {
        Path conf = findConformanceDir();
        Assumptions.assumeTrue(conf != null,
            "conformance/mztab_features not reachable from CWD");
        Path fixture = conf.resolve("metabolomics.mztab");
        Assumptions.assumeTrue(Files.isRegularFile(fixture),
            "fixture not present: " + fixture);

        MzTabImport parsed = MzTabReader.read(fixture);
        long smeCount = parsed.identifications().stream()
            .filter(i -> i.evidenceChain().stream()
                .anyMatch(e -> e.startsWith("SME_ID=")))
            .count();
        assertEquals(2, smeCount, "two SME-sourced identifications");

        double[] confs = parsed.identifications().stream()
            .filter(i -> i.evidenceChain().stream()
                .anyMatch(e -> e.startsWith("SME_ID=")))
            .mapToDouble(Identification::confidenceScore)
            .sorted()
            .toArray();
        // rank 2 → 0.5, rank 1 → 1.0.
        assertEquals(2, confs.length);
        assertEquals(0.5, confs[0], 1e-9);
        assertEquals(1.0, confs[1], 1e-9);
    }
}
